name: real_time_location_tracker
description: "A Flutter project to track real-time location using Google Maps and Geolocator."
publish_to: 'none' # This line prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Google Maps integration
  google_maps_flutter: ^2.2.0

  # To fetch current location and stream updates
  geolocator: ^13.0.2

  # Polyline support for route drawing
  flutter_polyline_points: ^1.0.0

  # Permission handler to manage location permissions
  permission_handler: ^11.1.0

  # Cupertino icons for iOS styling
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and specify paths if you need to add images or other assets
  # assets:
  #   - assets/images/icon.png
